apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-app 
    spec:     # pod spec                  
      containers: 
      - name: hello-app 
        image: mirnawaz/hello-node:2.1 # image we pushed
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: logs-persistent-storage
          mountPath: /usr/src/app/logs
      volumes:
      - name: logs-persistent-storage
        persistentVolumeClaim:
          claimName: logs-pv-claim