kind: PersistentVolume
apiVersion: v1
metadata:
  name: logs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi